language: python
python:
  - 2.7

services:
  - docker

before_install:
  - docker --version

install:
  - docker build -t backuppc .
  - docker run -d -p 127.0.0.1:8080:8080 --name backuppc backuppc

before_script:
  - pip install mock
  - pip install requests
  - pip install feedparser

script:
  - docker ps | grep -q backuppc
  - python tests.py