sudo: required

services:
  - docker

before_install:
  - docker --version
  - mkdir etc lib log
  - chmod 777 etc lib log

install:
  - docker build -t backuppc .
  - docker run -v ./etc:/etc/backuppc -v ./lib:/var/lib/backupc -v ./log:/var/log/backuppc -d -p 127.0.0.1:8080:8080 --name backuppc backuppc

script:
  - docker ps | grep -q backuppc
  - curl -L http://localhost:8080